version: 2
jobs:
  pilot-integration:
    machine: true
    working_directory: ~/go/src/istio.io/istio
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
      - checkout
      - run: pilot/bin/install-bazel.sh
      - run: curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.4/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - run: curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.22.3/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      - run:
          command: |
            sudo -E minikube start \
            --extra-config=apiserver.Admission.PluginNames="Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,GenericAdmissionWebhook,ResourceQuota" \
            --kubernetes-version=v1.7.5 --vm-driver=none
      - run: sudo -E minikube update-context
      - run: JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until sudo kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
      - run: sudo -E kubectl cluster-info
      - restore_cache:
          keys:
            - bazel-cache-{{ checksum "WORKSPACE" }}
      - run: make build
      - save_cache:
          key: bazel-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/.cache/bazel      
      - run: make docker HUB=docker.io/rshriram TAG=test  # make docker images for everything
      - run: cd pilot; mkdir /home/circleci/logs; make e2etest HUB=docker.io/rshriram TAG=test TESTOPTS="-mixer=false -errorlogsdir=/home/circleci/logs"
      - run:
          command: |
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: /home/circleci/logs

  unittest:
    working_directory: /go/src/istio.io/istio
    docker:
      - image: istio/ci:go1.9-k8s1.7.4
    steps:
      - checkout
      - run:
          name: Running Kubernetes API Server standalone
          command: /tmp/apiserver/start-test-server.sh
          background: true
      - restore_cache:
          keys:
            - dep-cache-{{ checksum "Gopkg.lock" }}
      - run: cd /go/src/istio.io/istio; dep ensure
      - run:
          command: |
            mkdir ~/.kube
            cp /go/src/istio.io/istio/.circleci/config ~/.kube/config
      - run: ln -s ~/.kube/config /go/src/istio.io/istio/pilot/platform/kube/config
      - run:
          command: |
            mkdir ~/envoy
            cd ~/envoy
            wget https://storage.googleapis.com/istio-build/proxy/envoy-debug-5d798021523fa1e587fa45d48b4ce38e25967ed3.tar.gz -O envoy.tar.gz
            tar xvzf envoy.tar.gz
            ln -sf ~/envoy/usr/local/bin/envoy /go/src/istio.io/istio/pilot/proxy/envoy/envoy
      - run: cd /go/src/istio.io/istio; go test ./pilot/...
      - run: cd /go/src/istio.io/istio; go test ./security/...
      - run: cd /go/src/istio.io/istio; go test ./broker/...
      - save_cache:
          key: dep-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/istio.io/istio/vendor

workflows:
  version: 2
  all:
    jobs:
      - unittest
      - pilot-integration:
          requires:
            - unittest
