
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/googleapis/googleapis"
  source = "https://github.com/costinm/googleapis.git"

[[constraint]]
  name = "google.golang.org/grpc"
  revision = "f92cdcd7dcdc69e81b2d7b338479a19a8723cfa3"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "7c69e980210777a6292351ac6873de083526f08e"

[[constraint]]
  name = "k8s.io/ingress"
  revision = "0c6f15e372c831de52fcc393932540bb3a6d51b5"

[[constraint]]
  name = "github.com/russross/blackfriday"
  revision = "4048872b16cc0fc2c5fd9eacf0ed2c2fedaa0c8c"
